package tr.org.liderahenk.lider.core.api.plugin;

import tr.org.liderahenk.lider.core.api.taskmanager.ITaskStatusUpdate;


/**
 * 
 * Provides {@link ICommand} access to {@link ITaskStatusUpdate} events generated by the underlying {@link ITaskManager} 
 * 
 *  @author <a href="mailto:birkan.duman@gmail.com">Birkan Duman</a>
 *
 */
public interface ITaskAwareCommand {
	
	/**
	 * 
	 * @param taskStatusUpdate event from system
	 * 
	 * implementors of this interface are notified synchronously,
	 *  so please AVOID long running processes in this method
	 * 
	 */
	void onTaskUpdate( ITaskStatusUpdate taskStatusUpdate);
}
