package tr.org.liderahenk.lider.core.api.plugin;

import tr.org.liderahenk.lider.core.api.messaging.messages.ITaskStatusMessage;
import tr.org.liderahenk.lider.core.api.persistence.entities.ICommandExecutionResult;
import tr.org.liderahenk.lider.core.api.taskmanager.ITaskManager;

/**
 * 
 * Provides {@link ICommand} access to {@link ITaskStatusMessage} events
 * generated by the underlying {@link ITaskManager}
 * 
 * @author <a href="mailto:emre.akkaya@agem.com.tr">Emre Akkaya</a>
 *
 */
public interface ITaskAwareCommand {

	/**
	 * 
	 * @param result
	 *            event from system
	 * 
	 *            implementors of this interface are notified synchronously, so
	 *            please AVOID long running processes in this method
	 * 
	 */
	void onTaskUpdate(ICommandExecutionResult result);

	/**
	 * 
	 * @return id of the plugin implementing this command.
	 */
	String getPluginName();

	/**
	 * 
	 * @return version of the plugin implementing this command.
	 */
	String getPluginVersion();

	/**
	 * Unique identifier of this command.
	 * 
	 * @return
	 */
	String getCommandId();

}
