#!/bin/sh
# postinst script for pardusmys-lider-1.0
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <postinst> `abort-remove'
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package


case "$1" in
    configure)
		
		ldapip=""

		while true; do

		exec 3>&1

		# Store data to $VALUE variable
		VALUE=$(dialog --ok-label "Tamam" --cancel-label "İptal" \
		--backtitle "Lider Ayarları" \
		--title "Lider" \
		--form "Lider  Ayarları" \
		10 50 0 \
		"Ldap IP     :" 1 1     "$ldapip"       1 15 15 0 \
		2>&1 1>&3)

		exec 3>&-

		if [ -z $VALUE ]
		then
			dialog --title "Hatalı bilgi girişi" --msgbox "\n Eksik bilgi girişi, lütfen tekrar deneyiniz...! : "$item 6 50
		else
			RES='';
			if expr "$VALUE" : '[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*$' >/dev/null; then
				echo "success"
			else
				dialog --title "Hatalı bilgi girişi" --msgbox "\n Girdiğiniz bilgiler hatalı lütfen tekrar giriniz! : "$item 6 50
				RES='ERROR'
			fi

			if [ -z $RES ]
			then
				ldapip=$VALUE
				echo "Ldap IP : "$ldapip
				break
			fi
		fi
		done

		mariadbip=""

		while true; do

		exec 3>&1

		# Store data to $VALUE variable
		VALUE=$(dialog --ok-label "Tamam" --cancel-label "İptal" \
		--backtitle "Lider Ayarları" \
		--title "Lider" \
		--form "Lider  Ayarları" \
		10 50 0 \
		"MariaDB IP     :" 1 1     "$mariadbip"       1 15 15 0 \
		2>&1 1>&3)

		exec 3>&-

		if [ -z $VALUE ]
		then
			dialog --title "Hatalı bilgi girişi" --msgbox "\n Eksik bilgi girişi, lütfen tekrar deneyiniz...! : "$item 6 50
		else
			RES='';
			if expr "$VALUE" : '[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*$' >/dev/null; then
				echo "success"
			else
				dialog --title "Hatalı bilgi girişi" --msgbox "\n Girdiğiniz bilgiler hatalı lütfen tekrar giriniz! : "$item 6 50
				RES='ERROR'
			fi

			if [ -z $RES ]
			then
				mariadbip=$VALUE
				echo "MariaDB IP : "$mariadbip
				break
			fi
		fi
		done

		ejabberdip=""

		while true; do

		exec 3>&1

		# Store data to $VALUE variable
		VALUE=$(dialog --ok-label "Tamam" --cancel-label "İptal" \
		--backtitle "Lider Ayarları" \
		--title "Lider" \
		--form "Lider  Ayarları" \
		10 50 0 \
		"Ejabberd IP     :" 1 1     "$ejabberdip"       1 15 15 0 \
		2>&1 1>&3)

		exec 3>&-

		if [ -z $VALUE ]
		then
			dialog --title "Hatalı bilgi girişi" --msgbox "\n Eksik bilgi girişi, lütfen tekrar deneyiniz...! : "$item 6 50
		else
			RES='';
			if expr "$VALUE" : '[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*$' >/dev/null; then
				echo "success"
			else
				dialog --title "Hatalı bilgi girişi" --msgbox "\n Girdiğiniz bilgiler hatalı lütfen tekrar giriniz! : "$item 6 50
				RES='ERROR'
			fi

			if [ -z $RES ]
			then
				ejabberdip=$VALUE
				echo "Ejabberd IP : "$ejabberdip
				break
			fi
		fi
		done

		#echo "Create ip variables"
		LDAP=$ldapip"\tldap.mys.pardus.org.tr"
		MARIADB=$mariadbip"\tdb.mys.pardus.org.tr"
		EJABBERD=$ejabberdip"\tim.mys.pardus.org.tr"

		#echo "Ip variables using sed command"
		sed -i '/ldap.mys.pardus.org.tr/d' /etc/hosts
		sed -i '/db.mys.pardus.org.tr/d' /etc/hosts
		sed -i '/im.mys.pardus.org.tr/d' /etc/hosts

		#echo "Write server ip configs in hosts file"
		sudo echo -e $LDAP >> /etc/hosts
		sudo echo -e $MARIADB >> /etc/hosts
		sudo echo -e $EJABBERD >> /etc/hosts

		echo "Creating lider.conf.d directory"
		if [ ! -d /etc/lider.conf.d ]
		then 
			sudo mkdir /etc/lider.conf.d 
		fi

		if [ ! -f /etc/lider.conf.d/server.conf ]
		then
			sudo echo "lider:172.21.1.14:root:toor" >> /etc/lider.conf.d/server.conf
			sudo echo "xmpp:172.21.1.20:root:toor" >> /etc/lider.conf.d/server.conf 
			sudo echo "ldap:172.21.1.24:root:toor" >> /etc/lider.conf.d/server.conf 
			sudo echo "db:172.21.1.30::root:toor" >> /etc/lider.conf.d/server.conf 
		fi

		if [ ! -d /pardus_nas/Scripts ]
		then
			sudo mkdir -p /pardus_nas/Scripts
		fi

		if [ ! -d /pardus_nas/agent_logs/new ]
		then
			sudo mkdir -p /pardus_nas/agent_logs/new
		fi

		if [ ! -d /pardus_nas/.sc ]
		then
			sudo mkdir /pardus_nas/.sc
		fi

		if [ ! -d /pardus_nas/pem ]
		then
			sudo mkdir /pardus_nas/pem
		fi

		if [ ! -d /pardus_nas/homeFolders ]
		then
			sudo mkdir /pardus_nas/homeFolders
		fi

		if [ ! -d /pardus_nas/uploads ]
                then
        	        sudo mkdir /pardus_nas/uploads
                fi

		if [ ! -d /pardus_nas/backups ]
                then
	                sudo mkdir /pardus_nas/backups
                fi

		sudo chmod -R 777 /pardus_nas

		# Jdk default settings....
		echo "JDK variables are settings..."
		file `which java` || true
		 if [ -f /usr/sbin/update-java-alternatives ]
	        then
        	        /usr/sbin/update-java-alternatives -l || true
	              	sudo /usr/sbin/update-java-alternatives --jre  -s j2sdk1.7-oracle
        	fi
		echo "JDK version : "
		java -version
		echo "Setting JAVA_HOME"
		sed -i '/JAVA_HOME/d' /etc/profile
		sudo echo -e "export JAVA_HOME=\"/usr/lib/jvm/j2sdk1.7-oracle\"" >> /etc/profile
		echo "#!/bin/bash" > /tmp/profilesetter.sh
		echo "" >> /tmp/profilesetter.sh
		echo "source /etc/profile" >> /tmp/profilesetter.sh
		echo "echo \"setter çalıştı!\"" >> /tmp/profilesetter.sh
		chmod +x /tmp/profilesetter.sh
		/tmp/profilesetter.sh
		. /etc/profile
		echo "JAVA_HOME:"$JAVA_HOME
		
		sudo tar -zxf /tmp/mys-distro-1.0.0-SNAPSHOT.tar.gz -C /opt/
		if [ -d "/opt/lider-server" ];then
			rm -Rf /opt/lider-server
		fi
		mv /opt/mys-distro-1.0.0-SNAPSHOT /opt/lider-server
		sudo chmod a+x /opt/lider-server/bin/karaf
		
    ;;
    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

# dh_installdeb will replace this with shell code automatically
# generated by other debhelper scripts.

#DEBHELPER#

exit 0
